SELECT DISTINCT 
?subject ?wdt_property ?obj
WHERE
{
  ?subject ?wdt_property ?obj.
  
  ?wd_property wikibase:directClaim ?wdt_property.
  ?wd_property p:P2302 ?statement.
  ?statement ps:P2302 wd:Q52004125. # allowed entity types constraint
  FILTER NOT EXISTS {?statement pq:P2305 wd:Q51885771.} # wikibase lexeme

  #?subject wikibase:propertyType wikibase:WikibaseLexeme.  
  ?subject a ontolex:LexicalEntry.
}
