SELECT DISTINCT 
?subject ?wdt_property ?object (str(?object) as ?o)
WHERE
{
  ?property wikibase:directClaim ?wdt_property.
  ?property p:P2302 ?statement.
  ?statement ps:P2302 wd:Q21510852. ## Commons link constraint
  ?statement pq:P2307 "File".
  
  ?subject ?wdt_property ?object.
  FILTER(!STRSTARTS(STR(?object), 'http://commons.wikimedia.org/wiki/Special:FilePath'))
  
  # EXAMPLE (comment next line to query all violations for all properties of this type...)
  # ... however note the risk of timeout: we suggest to run these queries one by one for each property of this type
  FILTER (?wdt_property = wdt:P14)
}