# type of constraint for Wikidata properties: used to specify that this property generally contains a single “best” value per item,
# though other values may be included as long as the “best” value is marked with preferred rank
# if ?s ?p ?o exists, then the graph can have ?s ?p ?o2 and ?o2 != ?o as long as ?o xor ?o2 has the preferred Rank
# e.g. if ?p = date of death (P570), multiple estimated values can be added as long as only one of them 
# is marked as preferred rank
# SPARQL representation:
SELECT DISTINCT
  ?subject ?wd_property
{
  FILTER NOT EXISTS {?stmt_obj wikibase:rank wikibase:PreferredRank}  
  {
    SELECT DISTINCT
      ?subject ?wd_property ?stmt_obj
    WHERE
    {
      ?wd_property wikibase:claim ?p_property.
      ?wd_property p:P2302 ?statement.
      ?statement ps:P2302 wd:Q52060874. ## single-best-value constraint
 
      ?subject ?p_property ?stmt_obj.
      ?subject ?p_property ?stmt_obj2.
      FILTER (?stmt_obj != ?stmt_obj2)  
     
      # EXAMPLE (comment next line to query all violations for all properties of this type...)
      # ... however note the risk of timeout: we suggest to run these queries one by one for each property of this type
      FILTER (?p_property = p:P570)
    }
  }
}